version: "3.8"

services:
  backend:
    build: ./backend
    container_name: node-backend
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres-db
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  caddy:
    image: caddy:2
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - backend

volumes:
  pgdata:
